In [1]:
# This file calculates number of all the cochanges (cloned + noncloned)
# It reads the result generated by the "produce_report"

In [6]:
import pandas as pd
import mysql.connector
from mysql.connector import Error

In [2]:
data_loc ="C:/Users/MD NADIM/Documents/NetBeansProjects/FindCochangeByClone/data_files/final_dataset/"

In [15]:
# List of Subject Systems and Clone Detectors!!!
subject_systems=["brlcad", "carol", "ctags", "freecol", "jabref", "jedit"]
clone_detectors=["conqat", "deckard", "iclones", "nicad5", "simcad", "simian"]

# This is the declaration if you want to check the functinality for one subject sytems and clone detector. 
# subject_systems=["brlcad"]
# clone_detectors=["conqat"]


# Work for every subject systems. 
for ss in subject_systems: 
    try:
        mySQLconnection = mysql.connector.connect(host='localhost',
                                 database='cochange_'+ss,
                                 #database='vua',                 
                                 user='root',
                                 password='')        

        cursor1 = mySQLconnection.cursor()

        # Read the cochange file stored in CSV. 
        df_cochange = pd.read_csv(data_loc+"all_performance_files/"+ss+"_performance.csv", sep=',', header=0, encoding='utf-8')
        result_set = [["change_id", "num_all_cochange", "num_cloned_cochange"]]

        print(ss)
        for i in range(len(df_cochange)):
            query="SELECT COUNT(`id`)-1 total_cc FROM `change_info`WHERE `version`=(SELECT `version` FROM `change_info` WHERE `id`='"+str(df_cochange["change_id"][i])+"')"
            cursor1.execute(query)
            records = cursor1.fetchall()
            #if(records[0][0]<1):   #For debugging, if any calculation is falling under 1 or not, which is not acceptable
#             print(query)
#             print(records[0][0])
#             print(df_cochange["change_id"][i])
#             print(df_cochange["num_change"][i]) 
#             print()
            
            result_set.append([df_cochange["change_id"][i], records[0][0], df_cochange["num_change"][i]])
        
        pd.DataFrame(result_set).to_csv(data_loc+"num_cloned_cochnage/"+ss+"_cloned_cochnage.csv", header=False, index=False)


    except Error as e:
        print("Error reading data from MySQL table", e, ss)
    finally:
        if (mySQLconnection.is_connected()):
            mySQLconnection.close()
            cursor1.close()
            #print("MySQL connection is closed")

brlcad
SELECT COUNT(`id`)-1 total_cc FROM `change_info`WHERE `version`=(SELECT `version` FROM `change_info` WHERE `id`='42250')
14
42250
2

MySQL connection is closed
carol
SELECT COUNT(`id`)-1 total_cc FROM `change_info`WHERE `version`=(SELECT `version` FROM `change_info` WHERE `id`='52027')
14
52027
1

MySQL connection is closed
ctags
SELECT COUNT(`id`)-1 total_cc FROM `change_info`WHERE `version`=(SELECT `version` FROM `change_info` WHERE `id`='38726')
3
38726
1

MySQL connection is closed
freecol
SELECT COUNT(`id`)-1 total_cc FROM `change_info`WHERE `version`=(SELECT `version` FROM `change_info` WHERE `id`='1')
29
1
3

MySQL connection is closed
jabref
SELECT COUNT(`id`)-1 total_cc FROM `change_info`WHERE `version`=(SELECT `version` FROM `change_info` WHERE `id`='54026')
25
54026
1

MySQL connection is closed
jedit
SELECT COUNT(`id`)-1 total_cc FROM `change_info`WHERE `version`=(SELECT `version` FROM `change_info` WHERE `id`='42260')
18
42260
1

MySQL connection is closed

In [18]:
#This if for test!!!
print(df_cochange.shape)
print(df_cochange["conqat"][0])
print(len(df_cochange))

(2103, 7)
42252
2103